steps:
#Copy the build cache locally
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '${_ANDROID_BUILD_CACHE}/', '/build_cache']
  id: copy_build_cache_local
  volumes:
    - name: 'build_cache'
      path: '/build_cache'
#Android build
- name: 'gcr.io/$PROJECT_ID/android-builder'
  args: ['gradle-build','${_ANDROID_SDK_LICENSE}','assembleProdRelease']
  id: gradle_build
  waitFor:
    - copy_build_cache_local
  volumes:
    - name: 'build_cache'
      path: '/build_cache'
#Repopulate the build-cache
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-q','cp', '/build_cache/dot_gradle.zip', '${_ANDROID_BUILD_CACHE}']
  id: upload_cache
  waitFor:
    - gradle_build
  volumes:
    - name: 'build_cache'
      path: '/build_cache'
#Deploy
- name: 'gcr.io/$PROJECT_ID/fastlane'
  args: ['upload']
  waitFor:
    - upload_cache