steps:
# Clone repository.
- name: 'gcr.io/cloud-builders/git'
  args: [ 'clone', '$_CLONE_URL']

# Fetch the Pull Request code into a temporary branch.
- name: 'gcr.io/cloud-builders/git'
  dir: 'cloud-builders-community'
  args: [ 'fetch', 'origin', 'pull/$_PR_NUMBER/head:temp_branch']
- name: 'gcr.io/cloud-builders/git'
  dir: 'cloud-builders-community'
  args: [ 'checkout', 'temp_branch']

# TEMP: print stuff.
- name: 'gcr.io/cloud-builders/git'
  dir: 'cloud-builders-community'
  args: [ 'branch']
- name: 'gcr.io/cloud-builders/git'
  dir: 'cloud-builders-community'
  args: [ 'diff', '--name-status', 'master..temp_branch']

# Create a build with this code.
- name: 'gcr.io/cloud-builders/gcloud'
  dir: 'cloud-builders-community'
  args: [ 'container', 'builds', 'submit', '--config=cloudbuild.yaml']
