steps:
# Add some checks around example, readme, etc...

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Loop through the builders, and build independently.
    # TODO(philmod): make these calls in parallel.
    for d in */; do
      echo Build $d
      gcloud container builds submit $d --config=${d}cloudbuild.yaml > /dev/null 2>&1
    done

timeout: 1200s
