# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
#
# Build the Alcide Advisor Image
#
- name: gcr.io/cloud-builders/docker
  args: ['build', '--tag=gcr.io/$PROJECT_ID/advisor', '.']
- name: "gcr.io/${PROJECT_ID}/advisor"
  args: ["validate", "cluster", "--help"]

images: ["gcr.io/${PROJECT_ID}/advisor"]