steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/android-builder'
  - "--build-arg"
  - "ANDROID_SDK_LICENSE=${_ANDROID_SDK_LICENSE}"
  - '.'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/android-sdk-base'
images: ['gcr.io/$PROJECT_ID/android-builder']
timeout: 2000s
