# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/${PROJECT_ID}/envsubst', '.']
- name: 'gcr.io/${PROJECT_ID}/envsubst'
  env: ["TEST=value"]
  args: ['test.txt']
- name: 'gcr.io/${PROJECT_ID}/envsubst'
  entrypoint: sh
  args: ['-c', '[[ "$(cat test.txt)" == "test=value" ]]']
images: ['gcr.io/${PROJECT_ID}/envsubst']